### ISSUE TITLE
See associated products in configurable

### ISSUE THREAD

**Issue by jerrylopez** [jreinke/magento-improve-api#8]
Great extension first off!

I see that you are able to associate simple products to configurable products when you create them, but I was unable find in the blog post if it is possible to see already existing associated products when pulling the configurable via the API. Is this possible?

**Comment by RamonMarkets** [comment]
Hi Jerry. Having the same problem. Have you found a solution yet?

**Comment by jerrylopez** [comment]
@RamonMarkets no sorry I haven't. This was about a year ago and another route was chosen. We were considering forking this repo at the time and adding it in ourselves, maybe something you may want to consider?

**Comment by RamonMarkets** [comment]
I just did a query to the mysql database to get all the existing products associated to a specific configurable product.

**Comment by jerrylopez** [comment]
@RamonMarkets  Awesome!
